### ISSUE TITLE
One user multiple databases

### ISSUE THREAD

**Issue by markotitel** [bennojoy/mysql#16]
Hi, 
Wanted to ask how can I achieve this with your role.
If I have:

```
mysql_db:
     - name: foo
       replicate: yes
     - name: bar
       replicate: no
     - name: foobar
       replicate: no

mysql_users:
     - name: benz
       pass: foobar
       priv: "*.*:ALL"
     - name: marko
       pass: foobar
       priv: "foo.*:ALL"
     - name: marko
       pass: foobar
       priv: "bar.*:ALL"
```

User `marko` will be granted only last DB in the list. In this case `bar`.
