### ISSUE TITLE
miss create db in slave 

### ISSUE THREAD

**Issue by linbo** [bennojoy/mysql#20]
MySQL Version:  5.5.38

I follow this configuration to create a new Replication environment, then loads data from an existing MySQL Server.  Since slave didn't create databases, sync db from master to slave will be failed, told db not exist when create tables;

The solution is set replicate_do_db = dbname in slave 

``` yml
  - hosts: master
    roles:
     - {role: mysql, mysql_db: [{name: benz}, {name: benz2}],
                     mysql_users: [{name: ben3, pass: foobar, priv: "*.*:ALL"},
                                   {name: ben2, pass: foo}],
                     mysql_db_id: 8 

  - hosts: slave
    roles:
     - {role: mysql, mysql_db: none, mysql_users: none,
              mysql_repl_role: slave, mysql_repl_master: vm2,
              mysql_db_id: 9, mysql_repl_user: [{name: repl, pass: foobar}] }
```
