### ISSUE TITLE
MySQL-python package required on remote host

### ISSUE THREAD

**Issue by swamikevala** [bennojoy/mysql#43]
All my hosts are on CentOS 7.6. I needed to add this to make the mysql_user module work:

```
- name: install MySQL-python package
  yum:
    name: MySQL-python
    state: present
```
